<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>1.0.2</Version>
    <Company>Strissel Studios</Company>
    <Product>WadForge Suite</Product>
  </PropertyGroup>
</Project>