<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.50.4" />
    <ProjectReference Include="..\WadForge.Aliases\WadForge.Aliases.csproj" />
    <ProjectReference Include="..\WadForge.Wad\WadForge.Wad.csproj" />
  </ItemGroup>
</Project>
